### PR TITLE
feat: python support

### PR DESCRIPTION
**Pull request by liquidiert**
- implemented new Python bebop generator
  - currently does not have tempo and union support
- implemented Python [bebop runtime](https://pypi.org/project/python-bebop/)  

solves #56

### CODE REVIEW

**Comment by liquidiert** [comment]
While writing some tests I came over some issues with decoding in the runtime. So I converted the PR to draft for now.

**Comment by andrewmd5** [comment]
Hi, currently recovering from the flu so I’ll review once I’m back on my feet. Two things:
- Squash your commits
- Ensure you’ve got passing integration test

**Comment by liquidiert** [comment]
Hey @andrewmd5 ,
- should I open a new PR then?
- meaning I should add some for python?

**Comment by andrewmd5** [comment]
> Hey @andrewmd5 no worries! Regarding your inquiries,
> 
> * should I open a new PR then?
> * meaning I should add some for python?

You shouldn’t need to open a new PR. Just squash and force push to your branch.

And yes, the roundtrip integration test suite will determine if your implementation is correct.

**Comment by liquidiert** [comment]
Okay thanks will do that then :)

**Comment by andrewmd5** [comment]
Let me know if you need any help with the integration test suite

**Pull request closed without merging**
